apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "platform-api"
  description: The platform's tRPC API
  annotations:
    github.com/project-slug: george-backstage-test/monorepo
    backstage.io/techdocs-ref: dir:.
spec:
  type: trpc
  owner: group:engineering
  lifecycle: production
  definition: |
   import { z } from 'zod';
    import { publicProcedure, router } from '../trpc';
    export const apiRouter = router({
      version: publicProcedure.query(() => {
        return { version: '0.42.0' };
      }),
      hello: publicProcedure
        .input(z.object({ username: z.string().nullish() }).nullish())
        .query(({ input, ctx }) => {
          return {
            text: `hello ${input?.username ?? ctx.user?.name ?? 'world'}`,
          };
        }),
    });
